// <auto-generated />
using KateBushFanSite.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace KateBushFanSite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KateBushFanSite.Models.PrintSource", b =>
                {
                    b.Property<int>("PrintSourceID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("Title");

                    b.HasKey("PrintSourceID");

                    b.ToTable("PrintSources");
                });

            modelBuilder.Entity("KateBushFanSite.Models.Story", b =>
                {
                    b.Property<int>("StoryID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Title");

                    b.Property<string>("UserStory");

                    b.HasKey("StoryID");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("KateBushFanSite.Models.WebSource", b =>
                {
                    b.Property<int>("WebSourceID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title");

                    b.Property<string>("Url");

                    b.HasKey("WebSourceID");

                    b.ToTable("WebSources");
                });
#pragma warning restore 612, 618
        }
    }
}
